# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.cache/wt [current_project]
set_property parent.project_path /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  /media/parth/F/Parth/vivado/vivado_proj/ip_repo/debug_fifo_1.0
  /media/parth/F/Parth/vivado/vivado_proj/ip_repo/axi_memory_1.0
  /media/parth/F/Parth/vivado/vivado_proj
} [current_project]
add_files /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.srcs/sources_1/bd/design_1/design_1.bd
set_property used_in_implementation false [get_files -all /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.srcs/sources_1/bd/design_1/ip/design_1_processing_system7_0_0/design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_0/design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.srcs/sources_1/bd/design_1/design_1_ooc.xdc]
set_property is_locked true [get_files /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.srcs/sources_1/bd/design_1/design_1.bd]

read_verilog -library xil_defaultlib /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.srcs/sources_1/bd/design_1/hdl/design_1_wrapper.v
read_xdc /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.srcs/constrs_1/new/port_constraints.xdc
set_property used_in_implementation false [get_files /media/parth/F/Parth/vivado/vivado_proj/spi_read_id/spi_read_id.srcs/constrs_1/new/port_constraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top design_1_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef design_1_wrapper.dcp
catch { report_utilization -file design_1_wrapper_utilization_synth.rpt -pb design_1_wrapper_utilization_synth.pb }
